name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-version: 1.57.0
        feature-args:
          - ''
          - --no-default-features --features alloc
          - --no-default-features
    steps:
    - uses: actions/checkout@v2
    - name: Install libudev
      run: sudo apt-get update && sudo apt-get install -y libudev-dev
    - name: Install MSRV
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${ matrix.rust-version }
        override: true
        components: rustfmt, clippy
    - name: Build
      run: cargo build --verbose ${{ matrix.feature-args }}
    - name: Run tests
      run: cargo test --verbose ${{ matrix.feature-args }}
